---
- name: Update and install avahi-daemon
  hosts: all
  remote_user: root
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install avahi-daemon
      ansible.builtin.apt:
        name: avahi-daemon
        state: present
