services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /media/nas/proxy/data:/data
      - /media/nas/proxy/letsencrypt:/etc/letsencrypt
    security_opt:
      - apparmor:unconfined
    environment:
      # Postgres parameters:
      DB_POSTGRES_HOST: 'db'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'npm'
      DB_POSTGRES_PASSWORD: 'npmpass'
      DB_POSTGRES_NAME: 'npm'
    depends_on:
      - db

  db:
    user: 977:988
    image: postgres:latest
    environment:
      POSTGRES_USER: 'npm'
      POSTGRES_PASSWORD: 'npmpass'
      POSTGRES_DB: 'npm'
    security_opt:
      - apparmor:unconfined
    volumes:
      - /media/nas/proxy/postgres:/var/lib/postgresql/data